config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy],
                       :defaults => { :protocol => "https"}
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :microposts, :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :reverse_relationships, :foreign_key => "followed_id",
                            :class_name => "Relationship",
                            :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_many :following, :through => :relationships, :source => :followed

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 51 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false}
  # Automatically create the virtual attribute 'password_confirmation'
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    # compare the encrypted_password with the encrypted version of the
    # submitted password
    encrypted_password == encrypt(submitted_password)
  end

  class << self

    def authenticate(email, submitted_password)
      user = User.find_by_email(email)
      return nil if user.nil?
      return user if user.has_password?(submitted_password)
    end

    def authenticate_with_salt(id, cookie_salt)
      user = User.find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  def following?(follower)
    relationships.find_by_followed_id(follower)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    follower = relationships.find_by_followed_id(followed)
    relationships.destroy(follower.id)
  end

  def feed
    Micropost.where("user_id = ?", id)
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    # the mechanismn to encrypt the
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:new, :show, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :new_user, :only => [:new, :create]
  before_filter :admin_user, :only => :destroy

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def new
    @user = User.new
    @title = 'Sign up'
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = "Welcome to the App!"
      sign_in(@user)

      redirect_to @user
    else
      # reseting the fields in the formular
      @user.password = ""
      @user.password_confirmation = ""

      @title = 'Sign up'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
      if !@user.admin
        @user.destroy
        flash[:success] = "User destroyed"
      end
    end

    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def new_user
      redirect_to(root_path) unless !signed_in?
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

  def gravatar_change
    link_to "Change", "http://gravatar.com/emails"
  end
end

app/views/users/_fields.html.haml
= render 'shared/error_messages', :object => form.object
%div{:class => 'field'}
  = form.label :name
%br
= form.text_field :name
%div{:class => 'field'}
  = form.label :email
%br
= form.text_field :email
%div{:class => 'field'}
  = form.label :password
%br
= form.password_field :password
%div{:class => 'field'}
  = form.label :password_confirmation
%br
= form.password_field :password_confirmation

app/views/users/_follow.html.haml
= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |form|
  %div
    = form.hidden_field :followed_id
  %div{:class => 'actions'}
    = form.submit 'Follow'

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  %div{:id => 'follow_form'}
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.haml
= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete }, :remote => true do |form|
  %div{:class => 'actions'}
    = form.submit 'Unfollow'

app/views/users/_user.html.haml
- @users.each do |user|
  %li
    = gravatar_for user, :size => 30
    = link_to user.name, user
    - if current_user.admin?
      = link_to "delete", user, :method => :delete, :confirm => "You sure?", :title  => "Delete #{user.name}"

app/views/users/edit.html.haml
%h1
  Edit user
= form_for @user do |form|
  = render 'fields', :form => form
  %div{:class => 'actions'}
    = form.submit "Update"
  %div
    = gravatar_for @user
    = gravatar_change

app/views/users/index.html.haml
%h1
  All users

= will_paginate
%ul{:class => 'users'}
  = render @users
= will_paginate

app/views/users/new.html.haml
%h1
  Sign up
= form_for @user do |form|
  = render 'fields', :form => form
  %div{:class => 'actions'}
    = form.submit "Sign up"

app/views/users/show.html.haml
%table{:class => 'profile', :summary => 'Profile information'}
  %tr
    %td{:class => 'main'}
      %h1
        = gravatar_for @user
        = @user.name
      = render 'follow_form' if signed_in?
      - unless @user.microposts.empty?
        %table{:class => 'microposts', :summary => 'Users microposts'}
          = render @microposts
        = will_paginate @microposts
    %td{:class => 'sidebar round'}
      %strong
        Name
        = @user.name
      %strong
        URL
        = link_to user_path(@user), @user
      %strong
        Microposts
        = @user.microposts.count
      = render 'shared/stats'

app/views/users/show_follow.html.haml
%table{:summary => 'Information about following/followers'}
  %tr
    %td{:class => 'main'}
      %h1
        = @title
      - unless @users.empty?
        %ul{:class => 'users'}
          = render @users
        = will_paginate @users
    %td{:class => 'sidebar round'}
      %strong
        Name
      = @user.name
      %strong
        URL
      = link_to user_path(@user), @user
      %strong
        Microposts
      = @user.microposts.count
      = render 'shared/stats'
      - unless @users.empty?
        - @users.each do |user|
          = link_to gravatar_for(user, :size => 30), user