config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy],
                       :defaults => { :protocol => "https"}
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.haml
%footer
  %nav{:class => 'round'}
    %ul
      %li
        = link_to "About", about_path
      %li
        = link_to "Contact", contact_path
      %li
        <a href="http://news.railstutorial.org/">News</a>
      %li
        <a href="http://www.railstutorial.org/">Rails Tutorial</a>

app/views/layouts/_header.html.haml
%header
  = link_to logo, root_path
  %nav{:class => "round"}
    %ul
      %li
        = link_to 'Home', root_path
      = users_link
      = profile_link
      = settings_path
      %li
        = link_to 'Help', help_path
      = signin_signout_link

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <section class="round">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end %>
      <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </div
</body>
</html>